language: php
php:
  - 5.3

sudo: false

cache:
  directories:
    - vendor
    - docs/.dexy
    - $HOME/.composer/cache
    - $HOME/.cache

addons:
  apt_packages:
    - python

before_script:
  - composer update --prefer-dist

script:
  - bin/phpspec run

after_success:
  - sudo apt-get update
  - sudo apt-get install python
  - cd docs && sudo bash ./bin/generate.sh

env:
  global:
    - secure: "oEnjQQc4E5fjIgAGCqVLRzyl5dula/dX5VMwwuKdlwZuzSa0lBp87R2i1pQTPub60XaxeKRkJoOfe/z2ULdQLRVbLnY+UcHt4h/T7EoebvffbKKv8Zv3NBqEV4oDVHiMUXauGYwi9riLxsgyUri62n1NCEhCp/imb1LE4pfT6Ao="

notifications:
  email: false

