language: php
php:
  - 5.3

before_script:
  - composer update --prefer-dist

script:
  - bin/phpspec run

after_success:
  - sudo apt-get update
  - sudo apt-get install python
  - cd docs && bash ./generate.sh

sudo: required

cache:
  directories:
    - vendor
    - docs/.dexy
    - $HOME/.composer/cache

env:
  global:
    - secure: "EAtxaLyapYmBfPUkPOtrVY/C5K0lzUZJHcHGwZV0dBV2Txv+lunGpTdCo20z39dIuzL/4TFn1JyjqJZuiXllhsGwykQvBDip8LXhedZwoZjK6D+SP/J7mQsCHAFEjzBGVMgzilrBYUlz5SnsRKVMifIAZhfyJAmGRtFSXzQK3eI="

