language: php
php:
  - 5.3
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

before_script:
  - composer install

script:
  - bin/phpspec run

after_success:
  - sudo apt-get update
  - sudo apt-get install python

sudo: required

cache:
  directories:
    - vendor
    - docs/.dexy
    - $HOME/.composer/cache

env:
  global:
    - secure=EbUMl2PXONzF+gYkCEsAnVbB1694noPE+AhCmhdVM6VC1A7nToA9mmTpJ89iVsj8vk6F6lfeqCIwfWgpqpLX/uleOfN2cRvYZUcuSppq4cPpSV2ehumOSBiKj1bWSthe9T1w7HmmlRKgd65dy+GU7CluvSzSz2nHVthGWdvEpsk=

