language: php
php:
  - 5.3
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

before_script:
  - composer install

script:
  - bin/phpspec run

after_success:
  - sudo apt-get update
  - sudo apt-get install python

sudo: false # use container

cache:
  directories:
    - vendor
    - docs/.dexy
    - $HOME/.composer/cache

